### ISSUE TITLE
Add in an option to automatically enable scroll lock per command

### ISSUE THREAD

**Issue by Pauan** [morassman/process-palette#10]
I have a command that when I run it, I want it to automatically enable scroll lock.

But I only want it for that one command: I want scroll lock to default to disabled for other commands (like it currently does).

**Comment by morassman** [comment]
Sure. I'll add a property with which to auto enable scroll lock. The default will be false.

**Comment by morassman** [comment]
A property called `scrollLockEnabled` was added to v0.5.1. The default value is `false` in order to keep the behaviour of existing configurations the same. Set it to `true` to auto enable scroll lock.

**Comment by Pauan** [comment]
I just upgraded to version 0.5.1 and it works, thanks!
