### ISSUE TITLE
Separate commands for opening and closing the panel

### ISSUE THREAD

**Issue by kankaristo** [morassman/process-palette#16]
Thanks for a fantastic package! This makes Atom the perfect "IDE" for me.

Would it be possible to add separate commands for opening and closing the panel, in addition to the toggle command?

It would be nice to be able to close the process-palette panel with `Esc`, but binding that to the toggle command doesn't really make sense.

**Comment by morassman** [comment]
Sure! I can add that.

Can you just elaborate a bit on how this will be useful in addition to the toggle? Is it so that you can use a shortcut and know what the effect will be regardless of whether the panel is visible or not?

Also, from your last sentence I just wonder, is it in particular the hiding with a separate key that will be useful or the showing of it as well?

**Comment by kankaristo** [comment]
`Esc` closes auto-complete, find+replace and nearly all other panels, so I'm basically just used to hitting it a few times to get rid of anything "extra". :smile:

So it's mostly to have a more uniform interface, since you can close most things by pressing `Esc`. Obviously, this is personal preference, so I'm not suggesting that `Esc` to hide process-palette should be the default, but having a command for it would allow binding it.

I would probably only use toggle and close, but having a separate command for open might be useful as well. And it's a logical "complement" to close.

**Comment by morassman** [comment]
That makes sense. Pressing Esc is quite common to close extra things, especially ones that pop up.

I'll add Esc as a shortcut and I'll also add separate commands for showing and hiding the panel in case someone finds it useful.

**Comment by morassman** [comment]
Added `Show` and `Hide` commands and also a binding to `Esc` for hiding the panel to v0.5.5.

**Comment by kankaristo** [comment]
Fantastic, thanks! :+1:
