### ISSUE TITLE
json validation

### ISSUE THREAD

**Issue by dcsan** [morassman/process-palette#18]
love this, its so useful!

maybe this is part of atom core rather than your extension, but when there's a dangling comma in the JSON it will silently fail... very frustrating figuring out why it's not loading...

**Comment by morassman** [comment]
Thanks!

I've had that frustration myself and figuring out what is wrong can be quite a mission. I only looked into it now, but the JSON parser actually throws an error if parsing failed. I'll make it so that the error is caught and reported to the user.

**Comment by dcsan** [comment]
the error does show up in the developer mode panel, so i now know to open that if things aren't working...

**Comment by morassman** [comment]
Ok. So at least there's some indication of what's wrong. I'll still make it more user friendly by properly reporting the error and, if available, the line number of the syntax error.

**Comment by morassman** [comment]
I've since added a UI for editing the configuration files. Editing them directly is therefore not necessary anymore and the file generated by it will also be properly formatted.

The UI is now the suggested way of editing, so validation shouldn't be required anymore.
