### ISSUE TITLE
Re-run last command

### ISSUE THREAD

**Issue by pchomik** [morassman/process-palette#21]
Hi,

Thank you for great plugin. 
Is it possible to add new command to re-run last executed process?

I'm using this plugin to run my unit tests and other task. It will be faster to repeat last command without selecting it in explicit way (less typing).

**Comment by morassman** [comment]
Hi. Thanks.

Sure. I'll look into it for the next version.

**Comment by morassman** [comment]
I finally got round to this. Sorry for the long wait.

I added a command to the command palette called "Rerun last". It doesn't have a short-cut key associated with it, but you can add your own one.

I'm not 100% sure if this will help you. All it does is it runs the last command as if you clicked on the run button again. It doesn't apply the same variables as the previous run. If, for instance, the last command asked for input from the user, then rerunning it will prompt the user again. It's like a clean slate. The only time this can really be an issue is if input is prompted or if variables like filePath is used that depends on the file currently open.

I can make it that it will rerun with the same variables as before. It's just a bit more effort, but I don't mind making it so.

Would this be sufficient for your use case or do you need the rerun to remember the values of the variables from the previous run?
