### ISSUE TITLE
Need a way to convert a path (e.g. project path) to use unix-style separators

### ISSUE THREAD

**Issue by darrenkenny** [morassman/process-palette#22]
I'm attempting to use process-palette to run a command using ssh on a UNIX system from a windows machine. 

The file path that is being generated is using a path like 'a\b\c.ext' but for UNIX it needs to see a path
like 'a/b/c.ext' - it would be good if on a per-command setting, if we could set a flag that it would
generate either UNIX or Windows-style paths.

**Comment by morassman** [comment]
I can look into this. A flag can be useful. All paths will then be treated the same. I think adding an attribute to a variable to specify the format of only that variable can also be useful, like {filePath | unix} for Unix paths and {projectPath | win} for Windows paths.

**Comment by morassman** [comment]
Ok. I've made it that you can pipe a variable the way I suggested above. I don't know which variable you're using, but in your case you will be able to use something like {filePath | win} to convert a Unix path to a Windows path.

I'm not going to release this just yet. I'm still working on something else, so if you have any objections/suggestions there's still time.

**Comment by morassman** [comment]
Hi. I finally got this out. Sorry for taking so long.

So to convert to a Windows path you can use {filePath | win} and to convert to Unix use {filePath | unix}. This simply replaces the path separators. If you have a windows path like 'C:\a\b\c' then the 'C:\' will simply become 'C:/'
