### ISSUE TITLE
Shell command entry field should really be multi-line

### ISSUE THREAD

**Issue by darrenkenny** [morassman/process-palette#23]
When attempting to run a command via ssh - the Shell Command field becomes very long, it would be
nice if it was multi-line, and would possibly allow for entry like:

```
   ssh somehost.example.com /a/long/path/to/a/command/to/run /another/long/path/to/a/file/to/run/against
```

to be converted to:

```
   ssh somehost.example.com \
       /a/long/path/to/a/command/to/run \
       /another/long/path/to/a/file/to/run/against
```

For readability if nothing else.

**Comment by morassman** [comment]
Would it be sufficient if the text field is a multi line editor that automatically wraps instead of converting to \-separated text? So, in the background it's one long line, but it at least appears multi-line when editing.

**Comment by morassman** [comment]
Sure. I can make it multi-line. I'm not sure if you mean that it should be _automatically_ converted if the line gets too long? I've tested it. With a multi-line editor, if you manually insert \-characters at the end of the line then your multi-line example will work correctly.

**Comment by darrenkenny** [comment]
Sounds great,  I'm not too worried with the exact approach but that the functionality is there, but thanks.

**Comment by morassman** [comment]
The shell command field in v.0.8.2 is now a multi-line editor.
