### ISSUE TITLE
Ask/Force save document before executing commands?

### ISSUE THREAD

**Issue by stefanvollmar** [morassman/process-palette#25]
Sorry if this has been asked before. - I already like process-palette a lot (thanks for a great Atom plugin!) and it works beautifully with a workflow we have at our institute: we write documentation with Atom in markdown (targeting HTML and PDF) and using process-palette, we have a keyboard shortcut that triggers a script which (1) runs a preprocessor tool we wrote on {filePath}, (2) runs pandoc on the result, and (3) finally displays the result in a browser. The script takes a fraction of a second (for HTML) and is very convenient.
However, there is one snag: our preprocessor, and subsequently pandoc, work on files - so one needs to save any changes in the current markdown document to disk before running the script. We can think of two new features that would make process-palette even more useful: (a) optionally force a "save" of the current document so any workflow relying on {filePath} is consistent with what is displayed by Atom and/or (b) (similar to Emacs when compiling) warn that one or more files contain unsaved data.

Many thanks in advance,
 Stefan

**Comment by morassman** [comment]
Hi Stefan

This actually hasn't been asked before, but it would be a good addition to the package. I use Eclipse for other projects and it too prompts to save a file before running a command. It's very useful.

I'm glad you're finding process-palette useful and thank you for the suggestion! I have a small update I plan on getting out soon, so I'll look into this for the version thereafter.

**Comment by zlhaa23** [comment]
+1 for this.
I use process-palette with latexmk. Feature (a) would be great.

**Comment by morassman** [comment]
I've implemented both options (a) and (b) for v.0.8.3. As part of each command's configuration you can choose whether any modified files should be saved before running. This option can be disabled. When enabled you can choose if all modified files should be saved or only those that are referenced by the command.

**Comment by stefanvollmar** [comment]
Excellent - works beautifully - thanks a lot!
