### ISSUE TITLE
Provide new variable to work with multiple projects

### ISSUE THREAD

**Issue by pchomik** [morassman/process-palette#27]
Hello,

Lastly I'm working with multiple projects. I have a command where "Working Directory" is set to "{projectPath}". It will be great to have new variable "{projectPaths}" and the result of such variable will be popup window/menu to select which project should be chosen. In such way I will be able in easy way to switch between projects and execute all my commands without any other action.

I see at least one problem with such variable: What if "{projectPaths}" is used in multiple places? For my case "{projectPaths}" should generate only one popup window/menu and should be resolved only once.

Is it possible to implement such request? What do you think about it?

**Comment by morassman** [comment]
Hi

Yes. It would be possible to implement this. I shouldn't be a problem if it gets used in multiple places. When a command is executed, each variable is resolved only once. In this case there would only be one popup and the chosen value will be used for each reference to the variable.

Thanks for the suggestion. I'll look into this for the next version.

**Comment by morassman** [comment]
I just released v0.9.0. I called the variable `selectProjectPath`. When you run your command you will be able to choose from a list which project's path you want to use. If you close the list without selecting a project then the command will be canceled.

I hope this helps!
