### ISSUE TITLE
Can you add {Current Word} variable?

### ISSUE THREAD

**Issue by zhaocai** [morassman/process-palette#28]
I use it to run a search in external help file. Thanks.

**Comment by morassman** [comment]
Hello @zhaocai 

I can, but this is quite a niche use case. How about using the {selection} variable? Just double click the word you want to select it and then run your command. Would that work for you?

**Comment by zhaocai** [comment]
@morassman Thanks for the answer. I use `vim-mode`, Fighting to save keystrokes and not touching mouse as much as possible are essential to vim experience. I can use `viw` to select to word first and then run the command. But if you run the command all the time, it becomes annoying to repeat.

BTW, I just start to use this amazing package! Everything works great. But one thing odd is the output panel color. It is always black and white which feels out of place. Maybe you should use color like `@pane-item-background-color`.

**Comment by morassman** [comment]
I see. That makes sense. Ok. I'll look into this.

As for the colour... It was actually a feature request by someone else to make it black and white. It used to be as you are suggesting. I guess its a conflict of interest :)

I can maybe make it a setting so one can choose to either use black and white or default colours, but I'm gonna give that a lower priority if you don't mind.

**Comment by zhaocai** [comment]
Not a problem, I can do it with `style.less`

``` CoffeeScript
.process-palette-output-panel {
    background-color: @pane-item-background-color;
    color: @text-color;
}
```

**Comment by morassman** [comment]
Ok cool. I'm glad you got the colour sorted out.

I just release v0.9.0. I added two more variables, `word` and `line`. `word` does what you requested and `line` will represent the line at the cursor.

**Comment by zhaocai** [comment]
Thanks.
