### ISSUE TITLE
Output is printed after the command execution is completed

### ISSUE THREAD

**Issue by abid-mujtaba** [morassman/process-palette#3]
I am using your excellent package to run a 'make' command that compiles a tex project using pdflatex.

I have noticed that the sequence of output generated by pdflatex only appears after process-palette has determined that the command has finished executing. Ideally I would like to view the output as it is generated so I know that the execution is proceeding normally.

**Comment by morassman** [comment]
Your observation is correct. The output is indeed only shown after the process completes. This is primarily due to the fact that the output produced by the process can be used as a variable and for that it makes sense to first accumulate everything. I can change it to stream the output as it is being produced. It'll require a small amount of refactoring, so I'll need a bit of time to do it properly.

**Comment by morassman** [comment]
I've added the ability to stream output to the target while it is being produced by the process. This is done by adding `"stream": true` to the configuration of a command. It is false by default, so one needs to set it to true explicitly.

I'm not going to close this issue yet. Please update to version 0.4.11. Take a look at it and let me know if it is sufficient.

**Comment by abid-mujtaba** [comment]
Awesome. It's working like a charm.

One thing I did note is that the streamed text in the output panel doesn't scroll automatically. As content is generated the panel keeps showing the top part. I was wondering if it would make more sense for it to emulate a terminal's auto-scroll behaviour.

And sorry for bugging you. I am starting to learn CoffeeScript. Once I am up to speed I will start editing the code myself and creating Pull Requests.

**Comment by morassman** [comment]
You're not bugging :) Feedback, bug reports and suggestions are much appreciated.

I thought about that too. What I want to do is add a 'scroll lock' button that one can toggle the auto scroll behaviour with. Until the option is there I would prefer to rather give the user the control as apposed to doing things automatically. It might be annoying when one is looking at a part of the output and then it jumps to the bottom. This will be done fairly soon.

**Comment by abid-mujtaba** [comment]
That's smart thinking. You could add an auto-scroll flag to the command configuration (like "stream").

Additionally, the behavior I would really like in such situations is that while the text is auto-scrolling (on addition of lines) if I use my mouse to scroll the text (or click somewhere on the text) the auto-scrolling immediately stops and the text stays where it is. New lines are added to the end without scrolling to the bottom.

If I now press End or scroll to the bottom auto-scroll starts up again.

**Comment by morassman** [comment]
Sounds good. I'll see how much I can get in on the first round.

**Comment by morassman** [comment]
Scroll lock behaviour has been implemented. Feel free to log any more suggestions or if it gives issues.

See also the [changelog](https://github.com/morassman/process-palette/blob/master/CHANGELOG.md) for a few more changes. One "hidden" change that I forgot to put in the changelog is that you no longer need the arguments array. Arguments can now be specified as part of the command's string.
