### ISSUE TITLE
Pane.addItem is deprecated.

### ISSUE THREAD

**Issue by steventango** [morassman/process-palette#32]
Pane::addItem(item, 0) is deprecated in favor of Pane::addItem(item, {index: 0})
```
Pane.addItem (C:\Users\[USER]\AppData\Local\atom\app-1.13.0-beta8\resources\app.asar\src\pane.js:447:14)
<unknown> (C:\Users\[USER]\.atom\packages\process-palette\lib\main.coffee:273:27)
```

**Comment by morassman** [comment]
I can see from the latest API that the function has changed. I'll release an update with a fix.

Where did you see this message? I'm running the latest version of Atom, but there wasn't a notification nor is there anything the the developer console.

**Comment by steventango** [comment]
I saw this message through Deprecation Cop. I am running
app-1.3.0-beta6
However, the message disappears in
app-1.3.0-beta8
So perhaps no fix is required.
