### ISSUE TITLE
Feature request: Potential improvements for the PP dock UI

### ISSUE THREAD

**Issue by DamnedScholar** [morassman/process-palette#54]
I greatly appreciate the dock item and the fact that I can have `process-palette.json` files in different folders in my project and they all get discovered and added to my options for commands to run. It's very convenient, but it can get a little confusing. For some projects, I might be using the same CLI tool in different directories and I can't tell the difference between identical commands when they're all displayed in the dock view. I feel like it would be a large enhancement for the dock item to include collapsing sections like the `Settings -> Packages` view, and I've made a mockup of how a real project of mine might look with the relevant headings and buttons if such a feature were implemented:

![image](https://user-images.githubusercontent.com/4084322/32309694-70305e8e-bf5b-11e7-855b-b0e99f36d210.png)

**Comment by morassman** [comment]
That's a good suggestion. It's actually something that bothered me way back when I implemented it that way. I didn't think it would be a good idea to just throw everything together like that, but I never revisited it.

I'll definitely implement this behaviour. Thanks for the mockups! :)

It might also be useful to put Global commands and each of the other projects in their own respective tabs. That way one doesn't have to scroll through a list to get to the project you're looking for.

I can support both views and allow the user to choose which one to use. If I do that then I would make your suggestion the default. That way it wouldn't look too different to what people are already used to, but they can choose to use tabs instead from under the settings.

**Comment by hg42** [comment]
just go with the tabs :-)
I think, there is no need to invest time in this kind of option. I don't see any advantage to have both.
If you choose the list like in the mockup, which would also be ok with me, could you add some separator line above the group title? Or make the title more promiment in color (but the what about people being color blind?). You may also put the title on some lighter bar spanning the the dialog width.

**Comment by DamnedScholar** [comment]
If the hamburger headings are designed well, it should be possible to change their styling just like any other `h3` (or whatever) tag.

I definitely don't have an issue with a tabbed view being available, but for the two projects I have ongoing where this would be relevant, I like having all of the buttons there on one screen. I just want to be able to tell identical commands from different folders apart.

**Comment by morassman** [comment]
I've started implementing the collapsable behaviour. I really like the feel of it. I still plan on doing the tabs, but I won't make it the default. Tabs will be a nice way to keep the UI uncluttered and keep projects out of each other's space. However, I feel that tabs can also make it look as if the sets of commands are mutually exclusive, which is not the case. Any command can be run at any time on anything regardless of where it is defined.

I'm also playing around with the look and feel of it. I think it would help to make things stand out a bit more. If everything is just a flat list then it can get rather cumbersome to find what you're looking for. See the attached screenshot.

![screen shot 2017-11-11 at 1 36 46 am](https://user-images.githubusercontent.com/13697130/32683037-ead1f5f4-c680-11e7-9872-2dbb6c4178a3.png)

**Comment by morassman** [comment]
I've released it like shown in the screenshot in v0.16.0. I'll still consider adding the option to use tabs and work on it later. Suggestions for improvements are still welcome, but for now I'm going to close this issue.

Thanks @DamnedScholar for the suggestion! The appearance is a bit different from your mockup, but I hope you find it useful as it is now.
