### ISSUE TITLE
Using Keystroke Triggers Shell Command to run 2x

### ISSUE THREAD

**Issue by roundangle** [morassman/process-palette#62]
I'm working in Mac OSX High Sierra. I've been using Process Palette for a little while now, and it's been super helpful in my scripting for Adobe After Effects. I recently had to wipe my machine and reinstall Atom Packages. I must have been running an old version of Process Palette previously, and I assume that's why I didn't notice the issue until now.

When I trigger a Process Palette Shell Command via Keystroke or Command Palette it actually runs twice (which causes an error in After Effects). 

Incidentally when I toggle the Command Palette and scroll to my custom Process Palette command, my assigned keystroke to the right in the column displays 2x as well.

And when I toggle Process Palette, there are 2 collapsable Global panels and each has all commands.

I assume there is some block of code being run 2x, but if you think there's something I'm doing wrong to cause this, I'd love to know what it is.

**Comment by roundangle** [comment]
I was able to bring back an old version, and from there update to current. And the issue has disappeared. In which case I might have done something moronic that caused the problem. Not sure what though.

**Comment by morassman** [comment]
It might actually be a bug that just isn't manifesting anymore. I'll keep an eye out for it, but in the mean time I'm glad you're not experiencing the issue anymore.
