### ISSUE TITLE
Doesn't stream LÖVE (love2d) output

### ISSUE THREAD

**Issue by doble-d** [morassman/process-palette#63]
Even if the 'stream' option is enabled the panel won't stream [love2d](https://love2d.org/) `print()` output in real time. It just shows everything at once when the process is stopped (the game's closed).

![process](https://user-images.githubusercontent.com/14228267/36930552-aaf2b582-1e68-11e8-9cce-dcbc975739da.gif)

**Comment by morassman** [comment]
It might be due to how new-lines are treated. Do you have a `println` option? If not, try appending a new-line to your string, like `print("Test\n")`

**Comment by doble-d** [comment]
Tried appending a new-line.. didn't work. Tried using io.write().. noup.
Being positive I can call a terminal along the game so I see the output there.

Thank you @morassman .

**Comment by morassman** [comment]
I haven't worked with love2d before, so I'm not 100% what you mean with "call a terminal along the game". Do you mean you run love2d from your terminal or that love2d provides its own terminal for output. Sorry :) I just want to try and understand it better. I find it very strange that the output wouldn't stream in real time.

I did a quick Google and someone experienced a similar issue : https://love2d.org/forums/viewtopic.php?t=79579

The solution there was to have a `conf.lua` file with the following content
```
function love.conf(t)
	t.console = true
end
```

Maybe this will solve the issue you are experiencing as well.

**Comment by hikkithegene** [comment]
Unfortunately `t.console` it's for windows only. But... I found [something](https://stackoverflow.com/questions/42147825/console-isnt-showing-up-when-running-print-using-love2d-with-atom-editor) that works.

It seems Lua has a buffered output (not sure what it means..), I added `io.stdout:setvbuf('no')` to the top of the **main.lua**  game file and it works fine now.

![works](https://user-images.githubusercontent.com/14228267/36938810-beb27e3e-1eec-11e8-822b-8ae886c8ca68.gif)

**Comment by doble-d** [comment]
Unfortunately `t.console` is for windows only. But... I found [something](https://stackoverflow.com/questions/42147825/console-isnt-showing-up-when-running-print-using-love2d-with-atom-editor) that works.

It seems Lua has a buffered output (not sure what that means..), I added `io.stdout:setvbuf('no')` to the top of the **main.lua**  game file and it works fine now.

![works](https://user-images.githubusercontent.com/14228267/36938810-beb27e3e-1eec-11e8-822b-8ae886c8ca68.gif)

I don't know well how atom packages work but ¿Can this be added as a process-palette feature that can be toggle from a checkbox?

**Comment by morassman** [comment]
I understand now what happened. By buffering the output, Lua kept it in memory, preventing one from seeing it in the panel. It may be doing this so that the output can be written out in batches or all at once some time later. When the process terminated the buffer got flushed and all the output appeared at the same time like you observed.

This is not something that Process Palette has control over though. It simply monitors the process' output stream and displays whatever it receives. If the process keeps the output, like Lua did in this case by buffering it, then there is nothing that Process Palette can do except wait. So, unfortunately, this isn't something that can be added to Process Palette.

Disabling the buffer like you did is definitely the right solution, so I'm going to close this issue. I'm glad you got it working!

**Comment by hg42** [comment]
I am not an expert with this, but I think stdio libraries often distinguish between output to a terminal and to a general file and adjust their buffering behavior according to this.
I think isatty() is used to determine if it is a terminal.
isatty(3) - Linux manual page  http://man7.org/linux/man-pages/man3/isatty.3.html
I think that's one reason why ptys exist.

I think you can test this with the tty command.
Invoking "tty" in a terminal outputs the device name or "not a tty". For atom I get "not a tty".
This also affects if programs like ls automatically create colored output (but you can force ls with an option).

**Comment by hg42** [comment]
there is also the "script" command that allows to fake a tty:

```
% script --return -q -c "tty" /dev/null 
/dev/pts/1
```

**Comment by doble-d** [comment]
Didn't work, used like this: `script --return -q -c "love {projectPath}" /dev/null`.. Everything appears at once when the process is terminated.

**Comment by hg42** [comment]
test.lua:
```
socket = require('socket')

for i=1,50 do
  print('hello')
  socket.sleep(0.1)
end
```

used in process-palette with the settings below:

* `lua5.1 test.lua`
**buffered**: outputs all lines after 5 seconds
* `lua5.2 test.lua`
unbuffered: outputs every line immediately
* `lua5.3 test.lua`
unbuffered: outputs every line immediately
* `script --return -q -c "lua5.1 test.lua" /dev/null`
unbuffered: outputs every line immediately

in a terminal (xterm etc.)

* `lua5.1 test.lua`
unbuffered: outputs every line immediately
* `lua5.1 test.lua | cat`
**buffered**: outputs all lines after 5 seconds
* `lua5.2 test.lua | cat`
unbuffered: outputs every line immediately
* `script --return -q -c "lua5.1 test.lua" /dev/null | cat`
unbuffered: outputs every line immediately

so
* lua5.1 checks if it is a terminal and buffers otherwise
* lua5.2/lua5.3 always uses unbuffered stdio
* script fakes a terminal for lua
* lua5.2/lua5.3 or lua5.1 with script work for me in process-palette

which results do you get?

I run the commands above with this configuration:
```
    {
      "namespace": "z",
      "action": "run-prompt",
      "command": "sleep 0.5; atpath {fileProjectPath}/{fileDirPath} {command}",
      "arguments": [],
      "cwd": "{fileProjectPath}/{fileDirPath}",
      "inputDialogs": [
        {
          "variableName": "command",
          "message": "command",
          "initialInput": ""
        }
      ],
      "env": {},
      "keystroke": "alt-r",
      "stream": true,
      "outputTarget": "panel",
      "outputBufferSize": 80000,
      "maxCompleted": 10,
      "autoShowOutput": true,
      "autoHideOutput": false,
      "scrollLockEnabled": false,
      "singular": false,
      "promptToSave": false,
      "saveOption": "all",
      "patterns": [],
      "successOutput": "{stdout}",
      "errorOutput": "{stdout}\n{stderr}",
      "fatalOutput": "Failed to execute : {fullCommand}\n{stdout}\n{stderr}",
      "startMessage": null,
      "successMessage": null,
      "errorMessage": null,
      "fatalMessage": "Failed to execute : {fullCommand}\n{stdout}\n{stderr}",
      "menus": [],
      "notifyOnStart": false,
      "notifyOnSuccess": false,
      "notifyOnError": false,
      "input": null
    }
```

**Comment by hg42** [comment]
because I use atpath (a shell script that changes the directory to the given path and then runs the command, my shell is zsh),
I tested again with this process palette entry using standard settings (note my test.lua is in my home directory, so cwd: is "~"):
```
    {
      "namespace": "test",
      "action": "test-lua",
      "command": "echo \"------ lua5.1\"\nlua5.1 test.lua\necho \"------ lua5.1 with script\"\nscript --return -q -c \"lua5.1 test.lua\" /dev/null",
      "arguments": [],
      "cwd": "~",
      "inputDialogs": [],
      "env": {},
      "keystroke": null,
      "stream": true,
      "outputTarget": "panel",
      "outputBufferSize": 80000,
      "maxCompleted": 3,
      "autoShowOutput": true,
      "autoHideOutput": false,
      "scrollLockEnabled": false,
      "singular": false,
      "promptToSave": true,
      "saveOption": "none",
      "patterns": [],
      "successOutput": "{stdout}",
      "errorOutput": "{stdout}\n{stderr}",
      "fatalOutput": "Failed to execute : {fullCommand}\n{stdout}\n{stderr}",
      "startMessage": null,
      "successMessage": "Executed : {fullCommand}",
      "errorMessage": "Executed : {fullCommand}\nReturned with code {exitStatus}\n{stderr}",
      "fatalMessage": "Failed to execute : {fullCommand}\n{stdout}\n{stderr}",
      "menus": [],
      "notifyOnStart": false,
      "notifyOnSuccess": true,
      "notifyOnError": true,
      "input": null
    }
```

and it works like expected.

**Comment by doble-d** [comment]
It works now. 
I removed _/dev/null_ from the previous script and it works without disabling the buffer.

`script --return -q -c "love {projectPath}"`

Thanks man.

**Comment by hg42** [comment]
> If the argument file is given, script saves the dialogue in this file.  If no filename is given, the dialogue  is  saved  in  the file typescript

I guess, you now have a file named `typescript` laying around.
It contains a copy of the output and start+end times.
You could use your own filename instead of /dev/null.
May be "love" detects it's /dev/null?

**Comment by doble-d** [comment]
Wait, I tried again with **/dev/null** and it seems it's working now. I don't know why I was sure I pasted it right the first time. Maybe I was kind of tired.. it was late or I changed some other option. Anyway, sorry for troubling you. You were a big help, man. Thank you!

**Comment by hg42** [comment]
that's fine...thanks for trying again...I only wanted to make sure, that I understand the behavior of the "script" command and isatty...have a nice time
