### ISSUE TITLE
access to platformio-terminal?

### ISSUE THREAD

**Issue by Bob-the-Kuhn** [morassman/process-palette#65]
I've gotten my idea to work by using process-pallet.  Unfortunately I also need the syntax highlighting in platformio-terminal.  Is there a way to spawn a platformio-terminal?

I was able to do some highlighting by doing some text substitution when printing (from Python) to Panel.  As best I can tell platformio-terminal is aware if the incoming text is from stdout or stderr and can highlight accordingly.  I can get both streams but there's no way to put them back together in the original order.

----

I'm also trying to make my application OS portable.  Right now I can send only one shell command line.  If I need to send multiple shell commands then I need to use OS specific nomenclature to put then all in the one line.  It would be nice if process-pallet allowed multiple lines.

**Comment by morassman** [comment]
I'll look into platformio-terminal a bit and get back to you about integrating with it.

Can you just elaborate a bit on the second topic? I'm not sure what you mean by "OS specific nomenclature". The input for the shell command is a multi-line editor where you can have multiple commands following each other.

![example](https://user-images.githubusercontent.com/13697130/38748309-fb2736da-3f4d-11e8-9c7a-4afd50f715d6.png)

**Comment by Bob-the-Kuhn** [comment]
All my original concerns have been addressed:
- I didn't know the muli-line editor was present.  Thanks
- I've figured out how to format the output stream to match how PlatformIO terminal does it.

----

I've found another concern.  As best I can tell the panel isn't responding to the escape sequences properly.

Here's what it should look like:
![image](https://user-images.githubusercontent.com/20692583/38776482-fca766dc-405c-11e8-871d-ec7fa77c1a02.png)


Here's what is happening in the panel:
![image](https://user-images.githubusercontent.com/20692583/38776487-0c5feffe-405d-11e8-8e8b-c1dcbd020658.png)

Ignore the different colors.  The absolute colors don't matter, just that they're easy to tell apart.

The biggest concern I have is the extra lines that are present.  

There's also some changes in color in the middle of a line.  Those shouldn't be happening.  My first thought was that the '\' was being treated as a color sequence but then I noticed that the characters weren't being eaten.  Very strange.

I've looked at what I'm dumping to stdout with a binary viewer and there's nothing strange going on.  The number of '\n' in the file match the number of lines the loop counter said were sent. 

Here's my color sequences:
```
color_NORMAL = '\033[0m'     # white text on black background
color_BLUE   = '\033[36;1m'
color_RED    = '\033[31;1m'
color_YELLOW = '\033[33;1m'
color_GREEN  = '\033[32;1m'
```

----

I did some test code to add line numbers to the output.  Below is a snapshot of the panel, a binary capture of what my program thinks it's sending and a copy & paste from the panel.  My program thinks it sent 110 lines but the copy & paste shows 302.

[log.txt](https://github.com/morassman/process-palette/files/1912079/log.txt)
[log_copy_paste.txt](https://github.com/morassman/process-palette/files/1912080/log_copy_paste.txt)

![image](https://user-images.githubusercontent.com/20692583/38776957-59eeb752-4065-11e8-885c-453b21b9f9b2.png)

**Comment by hg42** [comment]
eventually you could try my open pull request, it addresses these things.

It's not up to date with the last changes (mainly scroll lock).
I hope I find time to catch up in the next weeks.

**Comment by Bob-the-Kuhn** [comment]
More of my wish list:
- increased font size
- better color for yellow
- no blanking of panel when stdout is re-directed

**Comment by hg42** [comment]
this can be done via usual styling for all atom elements

**Comment by hg42** [comment]
I'm outside, can send you my style sheet some hours later

**Comment by hg42** [comment]
basicall use Developer tools to inspect the DOM tree

**Comment by Bob-the-Kuhn** [comment]
I couldn't figure out how to run/install the PR code.

My current system's formatting is OK so I'm going to put that on the back burner.

----

I've run into a bigger issue.  I need to get user input but Atom/Platformio is getting in the way of the Tkinter/TCL toolkit. The main part of the error message is **Can’t find a usable init.tcl in the following directories:** and then it lists a bunch of paths that all end with **/tcl8.5** .

Works fine in a Windows PowerShell but not in the Atom/Platformio environment.

I've opened up an issue in the PlatformIO community.  If they can't help then this approach is dead.

----

I really appreciate your package and you taking the time to answer my questions.

**Comment by hg42** [comment]
@Bob-the-Kuhn

to use the PR you first have to install this atom package from github.
I don't remember how it is done correctly. Usually you need developer mode for that ("View" / "Developer" / "Open In Dev Mode...").

Because I want to use my repo in normal mode I simply clone the github repo somewhere and link it to $HOME/.atom/packages/process-palette (on linux).

according tcl:
None of the listed tcl8.5 directories exists and includes an init.tcl? mine is on /usr/share/tcltk/tcl8.5/init.tcl

I only offered my PR because ANSI sequences and path detection conflict sometimes. I think in your pictures the path formatting stops the ANSI color. You would have to restart the color after the path. But the path has it's own color. I guess you could set it to `color: inherit !important;` for .process-palette-path-view in the style sheet.
I tried to create a parsing engine that allows user patterns using regexp. The ANSI sequences are also integrated.

You can style nearly everything in Atom. It is built on Electron, which is based on Chromium. You can use "View" / "Developer" / "Toggle Developer Tools".

$HOME/.atom/styles.less (in "less" css syntax):
```
.process-palette-output-panel {
  background: #ffffff !important;
  color: black !important;
  font-family: "Roboto Mono" !important;
  font-size: 13px;

  .process-palette-path-view {
    //background: #ffff99 !important;
    color: #000099 !important;
  }
  ...
```

**Comment by Bob-the-Kuhn** [comment]
I've found a better way to display the output.  I still use process-pallet to launch my python script but it now sends all it's output to a tcl window.

My only issue is the Windows PowerShell window can't find the TCL/Tkint files.  I swear I had that solved before.  Time to do some reverts to see if I can find the solution again.

**Comment by morassman** [comment]
@Bob-the-Kuhn. I'm glad you found a way to display the output.

With regards to your wish list:

**increased font size**
I added [this](https://github.com/morassman/process-palette/issues/66) issue and will add the ability to specify the font size in a future release.

**better color for yellow**
The color for yellow isn't hard-coded in Process Palette. [ansi-to-html](https://github.com/rburns/ansi-to-html) is used to apply styling to the output. ansi-to-html _does_ provide the ability to override colors. I _might_ add functionality to Process Palette to make it easy to specify what those overrides should be, but I don't want to make any promises just yet :)

**no blanking of panel when stdout is re-directed**
I'm not sure what you mean by this. If it is a bug, then please open another issue and elaborate a bit on what the behaviour is and possibly with reproduction steps.
