### ISSUE TITLE
barriers for {word} or pass current token?

### ISSUE THREAD

**Issue by mbroedl** [morassman/process-palette#68]
Hi,

I love your project, it's one of the best things about atom!
I just ran into a problem when I wanted to get a {word} passed through. That usually works, but sometimes the word I want is hyphenated and then it does not work any more...
Is there any way to either exclude hyphens from word barriers, or (what would work as well in my case) add an option to pass the current token?
The latter should work like this:
`editor.displayBuffer.tokenizedBuffer.tokenForPosition(position).value`
That for example, could return all contents in a comments, a whole markdown heading or in my case a markdown reference.
Many thanks!!

EDIT: I tried changing the word-variable in the pre-executed javascript but that did not work. And putting the token that I want into a environment variable for some reason lagged one execution behind (i.e. I always got the previous variable in my script, not the current one).
EDIT2: Now I have solved it by just passing the word and the whole line and filtering what I need in the shell script. But obviously it would be easier if I could get that from process palette!

**Comment by morassman** [comment]
Hi @mbroedl 

I've added a variable called `{token}`, which does what you suggested. If, for example, you write JS and place the cursor on the string in `console.log("hello-atom")`, then the value of `token` will be `hello-atom`.

I'll include this in the next update.

**Comment by mbroedl** [comment]
Thanks a lot, this is great news! Highly appreciated! :)

**Comment by morassman** [comment]
Released as part of v0.17.0
