### ISSUE TITLE
error while using wine with process-palette, usr/bin/ : No such file or directory

### ISSUE THREAD

**Issue by QuinientaFX** [morassman/process-palette#84]
Hello there,

Super exciting package!

I'm trying to have a compiler run via wine in Linux KDE neon 5.18 (Ubuntu 18.04). However I am having  trouble getting wine to work via process-palette, */usr/bin/wine* outputs:
```
/bin/sh: $/usr/bin/wine: No such file or directory
```
while using the same expression in regular terminals such yakuake and Konsole works just fine.

I tried using some other commands located in /usr/bin/ via process-palette and they work just fine (e.g. lscpu and lsmem)

What are steps I can take to figure out and resolve this issue? (PS. zero JS experience)

Thanks!

Richard

**Comment by QuinientaFX** [comment]
I resolved the issue.

The issue is related to flatpak based installations of atom. This issue has been referenced by another Atom terminal plugin.

**Explanation**

"Some Atom installations via flatpak may have incompatibilites, including an inability to find host system binaries from select directories, such as /usr/*. If you encounter issues using platformio-ide-terminal with flatpak, such as missing binaries, that are normally accessible from the path you have set in your shell of choice, or if you are not able to change directory into some directories, you may be affected. You can confirm this by looking for the nfsnobody permissions from the root of your disk. You can workaround this by installing another version of atom that is not inside a sandbox container. "

**Indeed installing a .deb based version of Atom resolved the issue.**

**For details see**

https://github.com/platformio/platformio-atom-ide-terminal/issues/664

Renamed title of this issue (#84) to a more generic title, so more users can find it.

All the best, Richard

**Comment by grandmastergainz** [comment]
**query**
