### ISSUE TITLE
Whitespace in the panel is broken

### ISSUE THREAD

**Issue by Pauan** [morassman/process-palette#9]
Here is a screenshot of how the output looks in my terminal: http://i.imgur.com/4XdE1s0.png

Here is a screenshot of how the output looks in the warning bubble: http://i.imgur.com/oCVS8cW.png

Here is a screenshot of how the output looks in process-palette: http://i.imgur.com/CN6ggtV.png

---

The important difference is in these lines:

```
  17 |   return {
  18 |     _type: 0,1
> 19 |     _list: list.make(...x),
     |     ^
  20 |     _events: event.make()
  21 |   };
  22 | };
```

I think you can fix this by setting `white-space: pre;` in the process-palette panel.

**Comment by morassman** [comment]
Thanks. I'll try that.

**Comment by morassman** [comment]
I followed your suggestion and it seems to do the trick. I tested with a simple echo command that contains tabs and it displayed them correctly. Please test with v0.5.1. I'll close the issue if it works for you.

**Comment by Pauan** [comment]
I just upgraded to version 0.5.1 and it works, thanks!
