### ISSUE TITLE
Keystrokes not working

### ISSUE THREAD

**Issue by CPterion** [morassman/process-palette#90]
**Keystroke:** `F5`
**Atom Version:** 1.54.0
**Operating System:** Windows 7

There are no conflicts in Keybindings. The command works when ran in Command Palette.

**Comment by morassman** [comment]
There was a bug with the key bindings. It should be fixed in the next version.

**Comment by CPterion** [comment]
Could you explain why was this closed? I don't think it's been fixed yet.

**Comment by morassman** [comment]
This was closed because the bug I mentioned was fixed. I tested it and it works. Make sure that you are using lowercase. If your command is configured with `F5`, then change it to `f5` instead.
