### ISSUE TITLE
Uncaught TypeError: _this9.streamOutput is not a function

### ISSUE THREAD

**Issue by vanboom** [morassman/process-palette#93]
With the latest release, there appears to be an issue with a missing function.  The process works and completes successfully, but the error occurs. 

1. Configure a process with Stream Output enabled and target set to Panel.  
2. Run the process

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: [process-palette](https://github.com/morassman/process-palette) package 0.19.0

> With the target set to Terminal, the error does not occur. 

### Stack Trace

Uncaught TypeError: _this9.streamOutput is not a function

```
At /home/doug/.atom/packages/process-palette/lib/controllers/process-controller.js:586

TypeError: _this9.streamOutput is not a function
    at Socket.onStdErr (/packages/process-palette/lib/controllers/process-controller.js:586:14)
    at Socket.emit (events.js:205:15)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:271:13)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by morassman** [comment]
It's fixed now in v0.19.1. It happens only when output is sent to stderr and somehow it slipped through the cracks in my tests. Thanks for reporting it!

**Comment by vanboom** [comment]
Thanks!  And thanks for supporting such a great package.

**Comment by morassman** [comment]
Sure! You're welcome :)
