### ISSUE TITLE
Panel icons are not visible when the scroll width is wider than the panel

### ISSUE THREAD

**Issue by vanboom** [morassman/process-palette#94]
When the process STDOUT lines are wider than the panel width, the entire panel width is affected.  This causes the icons like the COPY / SCROLL LOCK / TRASH CAN to scroll also. 

The client portion that holds the process output should scroll, but not the icon bar.  

![image](https://user-images.githubusercontent.com/251706/119737324-b5146b80-be44-11eb-8b03-95ca40c54939.png)

**Comment by morassman** [comment]
I've released v0.19.2 that should fix this. It will wrap text that is wider than the panel width.

Please test it with the output that your process produces.

**Comment by vanboom** [comment]
Yes, works perfectly - thanks!

**Comment by vanboom** [comment]
Reopening - thanks for working on this.  The height of the scrolling client area is not quite right - not able to scroll to the last line in the output.   Try to test by running a process with a lot of lines of output, then scrolling to the bottom.  The last 2 lines are not visible with the scroll bar at the bottom.  It may be a font issue on my system - thanks for testing.

**Comment by morassman** [comment]
Sorry it took so long this time. I just released version 0.19.3 which fixes that issue.
